### ISSUE TITLE
Cors policy error when trying to access .stl model from localhost

### ISSUE THREAD

**Issue by tekilla667** [codaline-io/angular-stl-model-viewer#454]
When I want to create the component inside my html file 
<stl-model-viewer [stlModels] = "['https://localhost:5001/models/standing.stl']"  [material] = "tempMaterial" id ="stl" ></stl-model-viewer>
and run the project i get CORS error. My API's CORS policy is configured properly (using ASP.NET Core 3.1):
```
  opt.AddPolicy("CorsPolicy", policy =>
                {
                   policy.AllowAnyHeader().AllowAnyMethod().WithOrigins("https://localhost:4200");
                    
                });
```
I use my wwwroot folder to access other files like .jpg or .mp4, and it works fine. the problem that I'm getting is when I link the [stlModels] attribute directly to the HTML code.
![image](https://user-images.githubusercontent.com/58048159/111218575-33e46100-85d7-11eb-96b5-1084736610f1.png)

Is there any way to overcome this?

**Comment by KillerCodeMonkey** [comment]
In General Cors IS a Serverside problem and not a Frontend one.

So i think we can Not do anything for you Here.

But are you Sure that you are running localhost AS HTTPS?


Am 15.03.2021 in 21:43, tekilla667 ***@***.***> schrieb:

When I want to create the component inside my html file
<stl-model-viewer [stlModels] = "['
https://localhost:5001/models/standing.stl']" [material] = "tempMaterial"
id ="stl" >
and run the project i get CORS error. My API's CORS policy is configured
properly (using ASP.NET Core 3.1):

  opt.AddPolicy("CorsPolicy", policy =>
                {

policy.AllowAnyHeader().AllowAnyMethod().WithOrigins("https://localhost:4200");

                });

I use my wwwroot folder to access other files like .jpg or .mp4, and it
works fine. the problem that I'm getting is when I link the [stlModels]
attribute directly to the HTML code.
[image: image]
<https://user-images.githubusercontent.com/58048159/111218575-33e46100-85d7-11eb-96b5-1084736610f1.png>

Is there any way to overcome this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codaline-io/angular-stl-model-viewer/issues/454>, or
unsubscribe

**Comment by tekilla667** [comment]
Yea, I got https on my localhost.
`<video src="https://localhost:5001/movies/timelapse.mp4" autoplay="" loop="" muted>`
this works just fine.
also when I link a file to my stl-viewer( a file that has no problem with CORS) 
`<stl-model-viewer [stlModels] = "['https://localhost:5001/movies/timelapse.mp4']"  [material] = "tempMaterial" id ="stl" ></stl-model-viewer>`
I also get a CORS error
so accessing src="https://localhost:5001/movies/timelapse.mp4" works
 [stlModels] = "['https://localhost:5001/movies/timelapse.mp4']" doesn't work

**Comment by KillerCodeMonkey** [comment]
yeah but as i said. cors is a server thing. and has nothing to do with this component.
Maybe the STLLoader of threejs is setting some custom header so CORS kicks in.
