### ISSUE TITLE
stl-model-viewer returns (probably) cached model

### ISSUE THREAD

**Issue by tekilla667** [codaline-io/angular-stl-model-viewer#455]
Sorry for spamming so much :D 
I've been working on a workaround on my yesterdays issue, and encountered a bug with the stl model component( I think).
Step 1: In my API (asp.net core 3.1) I created a controller that returns a STL file. Works fine:
![image](https://user-images.githubusercontent.com/58048159/111348945-fb00c680-8680-11eb-808a-5f350ba54131.png)
Step 2:  Update the html code in angular:
`<stl-model-viewer [stlModels] = "['https://localhost:5001/models']"  [material] = "tempMaterial" id ="stl" ></stl-model-viewer>`
Step 3: Run the app: Everything works ok, no CORS issue, the model is being displayed all good.
Step 4: Change the API Controller to return a different model:
Works fine:
![image](https://user-images.githubusercontent.com/58048159/111349296-4e731480-8681-11eb-9041-b2e7d6589f32.png)
Step 5: Without changing the angulars HTML code refresh the page. Problem: The previous model is being displayed, as if it was cached in memory or sth.

Any ideas of how can I solve this?

EDIT: Rerunning ng serve doesnt help :(

**Comment by KillerCodeMonkey** [comment]
Just Set The Cache-Control Header max age to 0, so the Browser is Not
caching The Response.

This would deactivate caching in General

Another solution for Testing purposes: Just add a unique query param in The
Frontend

Like `HTTPS://localhost:5000/models?Datetime=${Date.now()}`

So Just adding The current timestamp at The end deactivates caching AS
well, because you get a new url mostly every millisecond that Pass.



Am 16.03.2021 in 18:02, tekilla667 ***@***.***> schrieb:

Sorry for spamming so much :D
I've been working on a workaround on my yesterdays issue, and encountered a
bug with the stl model component( I think).
Step 1: In my API (asp.net core 3.1) I created a controller that returns a
STL file. Works fine:
[image: image]
<https://user-images.githubusercontent.com/58048159/111348945-fb00c680-8680-11eb-808a-5f350ba54131.png>
Step 2: Update the html code in angular:
<stl-model-viewer [stlModels] = "['https://localhost:5001/models']"
[material] = "tempMaterial" id ="stl" ></stl-model-viewer>
Step 3: Run the app: Everything works ok, no CORS issue, the model is being
displayed all good.
Step 4: Change the API Controller to return a different model:
Works fine:
[image: image]
<https://user-images.githubusercontent.com/58048159/111349296-4e731480-8681-11eb-9041-b2e7d6589f32.png>
Step 5: Without changing the angulars HTML code refresh the page. Problem:
The previous model is being displayed, as if it was cached in memory or sth.

Any ideas of how can I solve this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codaline-io/angular-stl-model-viewer/issues/455>, or
unsubscribe

**Comment by tekilla667** [comment]
Wow it worked, once again, thank you a lot!
